### ISSUE TITLE
Calculated Link header values

### ISSUE THREAD

**Issue by demisx** [polo2ro/node-paginate-anything#4]
There are total 22 items in DB and my `max-range-size = 5`. Is it expected behavior that requesting this range:
```http
GET /v1/ads?classId=2
Range-Unit: items
Range: 5-11
```
return `Link` header like this?
```http
Link: '</?classId=2>; rel="next"; items="10-16", </?classId=2>; rel="last"; items="20-26", 
        </?classId=2>; rel="prev"; items="0-6", </?classId=2>; rel="first"; items="0-6"'
```

My questions:
1. Why the `prev` and `first` are set to `"0-6"` when I am already expecting to get 5 and 6 in this request?
2. Shouldn't the `next` and `last` items to be set to `"20-21"`, since there are only 22 items in the DB matching this request 

Thank you. Just trying to understand how this should work.

**Comment by polo2ro** [comment]
Hi,
This library behavior has been copied from https://github.com/begriffs/clean_pagination
The expected result was to get the same result and it made sense when i did it. prev page with 0-6 is probably a trick to get a full page when returning to the first page.
the range of the last page is probably set like this because the total number can grow while navigating in page, also, the total number can be set to "Infinity", headers represent the range of request, not the range of results.
